version: '3'

services:
  datascience-notebook:
    image: 'jupyter/datascience-notebook'
    ports:
      - '8081:8888'
    volumes:
      - ./work:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    command:
      start-notebook.sh --NotebookApp.password='${JUPYTER_TOKEN}'